# Amazon.com - Employee Access.

In [55]:
import pandas as pd

In [56]:
import numpy as np

In [57]:
train = pd.read_csv('train.csv')

In [58]:
test = pd.read_csv('test.csv')

In [59]:
train.head()

ACTION  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0       1     39353   85475         117961         118300         123472   
1       1     17183    1540         117961         118343         123125   
2       1     36724   14457         118219         118220         117884   
3       1     36135    5396         117961         118343         119993   
4       1     42680    5905         117929         117930         119569   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117905            117906       290919     117908  
1      118536            118536       308574     118539  
2      117879            267952        19721     117880  
3      118321            240983       290919     118322  
4      119323            123932        19793     119325

In [60]:
test.head()

id  RESOURCE  MGR_ID  ROLE_ROLLUP_1  ROLE_ROLLUP_2  ROLE_DEPTNAME  \
0   1     78766   72734         118079         118080         117878   
1   2     40644    4378         117961         118327         118507   
2   3     75443    2395         117961         118300         119488   
3   4     43219   19986         117961         118225         118403   
4   5     42093   50015         117961         118343         119598   

   ROLE_TITLE  ROLE_FAMILY_DESC  ROLE_FAMILY  ROLE_CODE  
0      117879            118177        19721     117880  
1      118863            122008       118398     118865  
2      118172            301534       249618     118175  
3      120773            136187       118960     120774  
4      118422            300136       118424     118425

In [61]:
train.shape

(32769, 10)

In [62]:
test.shape

(58921, 10)

In [63]:
test_1 = test.drop('id', axis=1)

In [64]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32769 entries, 0 to 32768
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ACTION            32769 non-null  int64
 1   RESOURCE          32769 non-null  int64
 2   MGR_ID            32769 non-null  int64
 3   ROLE_ROLLUP_1     32769 non-null  int64
 4   ROLE_ROLLUP_2     32769 non-null  int64
 5   ROLE_DEPTNAME     32769 non-null  int64
 6   ROLE_TITLE        32769 non-null  int64
 7   ROLE_FAMILY_DESC  32769 non-null  int64
 8   ROLE_FAMILY       32769 non-null  int64
 9   ROLE_CODE         32769 non-null  int64
dtypes: int64(10)
memory usage: 2.5 MB


In [65]:
train.isnull().sum()

ACTION              0
RESOURCE            0
MGR_ID              0
ROLE_ROLLUP_1       0
ROLE_ROLLUP_2       0
ROLE_DEPTNAME       0
ROLE_TITLE          0
ROLE_FAMILY_DESC    0
ROLE_FAMILY         0
ROLE_CODE           0
dtype: int64

In [66]:
train.describe()

ACTION       RESOURCE         MGR_ID  ROLE_ROLLUP_1  \
count  32769.000000   32769.000000   32769.000000   32769.000000   
mean       0.942110   42923.916171   25988.957979  116952.627788   
std        0.233539   34173.892702   35928.031650   10875.563591   
min        0.000000       0.000000      25.000000    4292.000000   
25%        1.000000   20299.000000    4566.000000  117961.000000   
50%        1.000000   35376.000000   13545.000000  117961.000000   
75%        1.000000   74189.000000   42034.000000  117961.000000   
max        1.000000  312153.000000  311696.000000  311178.000000   

       ROLE_ROLLUP_2  ROLE_DEPTNAME     ROLE_TITLE  ROLE_FAMILY_DESC  \
count   32769.000000   32769.000000   32769.000000      32769.000000   
mean   118301.823156  118912.779914  125916.152644     170178.369648   
std      4551.588572   18961.322917   31036.465825      69509.462130   
min     23779.000000    4674.000000  117879.000000       4673.000000   
25%    118102.000000  118395.000000  118274.000000     117906.000000   
50%    118300.000000  118921.000000  118568.000000     128696.000000   
75%    118386.000000  120535.000000  120006.000000     235280.000000   
max    286791.000000  286792.000000  311867.000000     311867.000000   

         ROLE_FAMILY      ROLE_CODE  
count   32769.000000   32769.000000  
mean   183703.408893  119789.430132  
std    100488.407413    5784.275516  
min      3130.000000  117880.000000  
25%    118363.000000  118232.000000  
50%    119006.000000  118570.000000  
75%    290919.000000  119348.000000  
max    308574.000000  270691.000000

In [67]:
X = train.drop('ACTION', axis=1)
y = train['ACTION']

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier

In [71]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [72]:
logr = LogisticRegression()
logr.fit(X_train, y_train)
pred = logr.predict(X_test)
print('accuracy_score of Logistic_regression_model : ',accuracy_score(pred, y_test))
print('Confusion_matrix for LOGR : \n',confusion_matrix(y_test, pred))

accuracy_score of Logistic_regression_model :  0.9446139761977418
Confusion_matrix for LOGR : 
 [[   0  363]
 [   0 6191]]


In [73]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('accuracy_score of DecisionTreeClassifier : ',accuracy_score(pred, y_test))
print('Confusion_matrix for DecisionTreeClassifier : \n',confusion_matrix(y_test, pred))

accuracy_score of DecisionTreeClassifier :  0.9311870613365884
Confusion_matrix for DecisionTreeClassifier : 
 [[ 161  202]
 [ 249 5942]]


In [74]:
ada_clf = AdaBoostClassifier()
ada_clf.fit(X_train, y_train)
pred = ada_clf.predict(X_test)
print('accuracy_score of AdaBoostClassifier : ',accuracy_score(pred, y_test))
print('Confusion_matrix for AdaBoostClassifier : \n',confusion_matrix(y_test, pred))

accuracy_score of AdaBoostClassifier :  0.9446139761977418
Confusion_matrix for AdaBoostClassifier : 
 [[   0  363]
 [   0 6191]]


In [75]:
gb_clf = GradientBoostingClassifier()
gb_clf.fit(X_train, y_train)
pred = gb_clf.predict(X_test)
print('accuracy_score of GradientBoostingClassifier : ',accuracy_score(pred, y_test))
print('Confusion_matrix for GradientBoostingClassifier : \n',confusion_matrix(y_test, pred))

accuracy_score of GradientBoostingClassifier :  0.9452242905096124
Confusion_matrix for GradientBoostingClassifier : 
 [[   6  357]
 [   2 6189]]


In [76]:
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print('accuracy_score of RandomForestClassifier : ',accuracy_score(pred, y_test))
print('Confusion_matrix for RandomForestClassifier : \n',confusion_matrix(y_test, pred))

accuracy_score of RandomForestClassifier :  0.9530057979859627
Confusion_matrix for RandomForestClassifier : 
 [[ 149  214]
 [  94 6097]]


In [77]:
test_pred = pd.DataFrame({'id':test['id'], 'ACTION':rf_clf.predict(test_1)})

In [78]:
test_pred

id  ACTION
0          1       1
1          2       1
2          3       1
3          4       1
4          5       1
...      ...     ...
58916  58917       1
58917  58918       1
58918  58919       1
58919  58920       1
58920  58921       1

[58921 rows x 2 columns]

In [79]:
test_pred.to_csv('final_predictions', index=False)

In [80]:
test_pred['ACTION'].value_counts()

1    56793
0     2128
Name: ACTION, dtype: int64